spring.application.name=equipment-service
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://postgres:5432/equipment_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Flyway
spring.flyway.baseline-on-migrate=false
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=TRACE
logging.level.org.flywaydb.core=DEBUG
logging.level.org.springframework.core.env=DEBUG


# ======================
# Kafka Configuration
# ======================

spring.kafka.bootstrap-servers=kafka:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# Consumer
#spring.kafka.consumer.group-id=maintenance-service
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer


# Needed for JSON event classes
spring.kafka.consumer.properties.spring.json.trusted.packages=*3
